### ISSUE TITLE
include a workaround for Mac on aligned_alloc?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-ot#14]
I see last month, the delta OT was introduced. It aligns the memory using aligned_alloc.

The issue in Mac: aligned_alloc not supported in libc of Mac.
Changing the compiler does not help.

Question:
     Is the alignment a must?

Proposed solution:
     Use manual aligned_alloc (Ln 22-39, https://github.com/RoutingKit/RoutingKit/blob/master/src/bit_vector.cpp) with a condition if aligned_alloc is not defined?

**Comment by weikengchen** [comment]
Note. if needed, I actually can submit a PR.

**Comment by wangxiao1254** [comment]
Thanks for the pointer. This is a good idea. I will update the code when I have time. If you have time, PR is welcome too :)

**Comment by fabrice102** [comment]
Oups, I did not see this issue. I proposed another solution in #16.

**Comment by weikengchen** [comment]
@fabrice102  Yes. Boost would be a standard workaround for that.

try if my alternative works :)

**Comment by wangxiao1254** [comment]
@weikengchen 's solution works but I think @fabrice102 's solution is more robust as in the long run we may want to support more platforms. I will try to switch to Fabrice's solution. Thanks everyone for their contribution!!

**Comment by weikengchen** [comment]
agree. Happy Holiday!

**Comment by wangxiao1254** [comment]
Everything should work now. Turns out we need at least boost1.58, which is not directly supported by trusty...

**Comment by wangxiao1254** [comment]
I must have forgotten to close this issue...
