### ISSUE TITLE
Illegal instruction Issue

### ISSUE THREAD

**Issue by fionser** [emp-toolkit/emp-ot#17]
Hi guys,
I used the scripts in the `emp-readme` to install all the necessary libraries. But when I ran
the examples codes, I crashed into the 'illegal instruction' error. I suppose it might due to a wrong dynamic link. I hope if anyone have meet the similar error, and give me some helps. Thanks!.

Here is the spec of my environment. 
* OS: Ubuntu 14.04
* gcc ver. 6.3
* Boost ver. 1.58
* OpenSSL ver. 1.0.2g

**Comment by wangxiao1254** [comment]
Which binary are you trying? DeltaOT requires more recent hardware support. If the crashing example is not deltaOT, please attach your cpuflags.

**Comment by fionser** [comment]
@wangxiao1254 I was using the SHOTExtension. 
Here is the cpuflags on my machine
```
 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
```

**Comment by wangxiao1254** [comment]
You don't have `rdseed`,  which is used to generate cryptographically strong random seed.
Please compile with `cmake -DUSE_RANDOM_DEVICE=ON .`

**Comment by fionser** [comment]
@wangxiao1254 It worked, and thanks for the help!
