### ISSUE TITLE
Unknown notations for OTs.

### ISSUE THREAD

**Issue by tree-in-forest** [emp-toolkit/emp-ot#28]
I'm not too familiar oblivious transfers and I have a hard time understanding what following abbreviation means (or what are the main differences). Can anyone direct me to right related articles (that use such labeling)?

- OT, **C**OT, **R**OT
- **NP**OT, **CO**OT, OT**e**

I get that OT is oblivious transfer and SHOT is a version of OT that is  secure in "semihonest setting" and MOT is a version of OT that is secure in "malicious setting".

**Comment by wangxiao1254** [comment]
First bullet: See https://eprint.iacr.org/2013/552.pdf
Second bullet: e for "extension"; the other two are abbrev of authors' name. 
- http://www.pinkas.net/PAPERS/effot.ps
- https://eprint.iacr.org/2015/267.pdf

**Comment by tree-in-forest** [comment]
Thank you for fast replay.
