### ISSUE TITLE
Could you add a manual for this library?

### ISSUE THREAD

**Issue by locomotive-crypto** [emp-toolkit/emp-ot#46]
This library is good. But it is hard to use it for lack of manual. 

If you can add a manual, I belive that it will be better.

Now, I want to use `OTNP` algorithm and I only find `send()` and `recv()` method for this class.

I have some knowledges about `Oblivious Transfer`:

```
First, One party(Bob) choices a selection bit.
Second, the other party(Alice) sends  two messages to Bob.
Finally, Bob get one message of the two.
```

So, I don't understand your implementation and use your library.

**Comment by wangxiao1254** [comment]
See readme!

**Comment by locomotive-crypto** [comment]
Thanks! Are you a chinese?
