### ISSUE TITLE
./run: line 29:  2573 Segmentation fault      (core dumped) $1 2 12345

### ISSUE THREAD

**Issue by ArlenaXiong** [emp-toolkit/emp-ot#51]
Hi Wangxiao,

When I  have cloned emp-ot project and cmake make it, I want to run test like you list:
./run ./bin/ot  12345

there will be an error: 
./run: line 29:  2573 Segmentation fault      (core dumped) $1 2 12345

 the same with emp-sh2pc

Is there any thing wrong?

Thank you.

**Comment by ArlenaXiong** [comment]
> Hi Wangxiao,
> 
> When I have cloned emp-ot project and cmake make it, I want to run test like you list:
> ./run ./bin/ot 12345
> 
> there will be an error:
> ./run: line 29: 2573 Segmentation fault (core dumped) $1 2 12345
> 
> the same with emp-sh2pc
> 
> Is there any thing wrong?
> 
> Thank you.

I get the same result when I run this program https://github.com/emp-toolkit/emp-ot/issues/45#issue-761922049 while there is no make error.

**Comment by wangxiao1254** [comment]
We updated the binary and now you need to specify the number of OT to run. See https://github.com/emp-toolkit/emp-ot/blob/master/.github/workflows/x86.yml#L24

**Comment by ArlenaXiong** [comment]
> We updated the binary and now you need to specify the number of OT to run. See https://github.com/emp-toolkit/emp-ot/blob/master/.github/workflows/x86.yml#L24

Thank u, I have found that I need to user two terminal to run this program.

**Comment by wangxiao1254** [comment]
I'm closing this issue since that you appear to have solved it.
