### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ArlenaXiong** [emp-toolkit/emp-ot#52]
This is error when I try to make my project:

In file included from /home/arlena/MPC/Secure-ML/src/linear_regression.hpp:3,
                 from /home/arlena/MPC/Secure-ML/src/secure_ML.cpp:2:
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:17:10: error: ‘SHOTExtension’ in namespace ‘emp’ does not name a template type
   17 |     emp::SHOTExtension<emp::NetIO>* send_ot;
      |          ^~~~~~~~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:18:10: error: ‘SHOTExtension’ in namespace ‘emp’ does not name a template type
   18 |     emp::SHOTExtension<emp::NetIO>* recv_ot;
      |          ^~~~~~~~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp: In constructor ‘SetupPhase::SetupPhase(int, int, int, emp::NetIO*)’:
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:26:15: error: ‘class SetupPhase’ has no member named ‘send_ot’
   26 |         this->send_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |               ^~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:26:34: error: ‘SHOTExtension’ in namespace ‘emp’ does not name a template type
   26 |         this->send_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |                                  ^~~~~~~~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:26:58: error: expected primary-expression before ‘>’ token
   26 |         this->send_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |                                                          ^
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:27:15: error: ‘class SetupPhase’ has no member named ‘recv_ot’
   27 |         this->recv_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |               ^~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:27:34: error: ‘SHOTExtension’ in namespace ‘emp’ does not name a template type
   27 |         this->recv_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |                                  ^~~~~~~~~~~~~
/home/arlena/MPC/Secure-ML/src/setup_phase.hpp:27:58: error: expected primary-expression before ‘>’ token
   27 |         this->recv_ot = new emp::SHOTExtension<emp::NetIO>(io);
      |                                                          ^
make[2]: *** [CMakeFiles/secure_ML.dir/build.make:63: CMakeFiles/secure_ML.dir/src/secure_ML.cpp.o] Error 1
make[2]: Leaving directory '/home/arlena/MPC/Secure-ML/build'
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/secure_ML.dir/all] Error 2
make[1]: Leaving directory '/home/arlena/MPC/Secure-ML/build'
make: *** [Makefile:84: all] Error 2

It seems the NetIO is not recognized?

**Comment by wangxiao1254** [comment]
Your code uses a deprecated interface two years ago. The code has to be modified for the new EMP-OT interface
