### ISSUE TITLE
Segmentation fault while trying to run test

### ISSUE THREAD

**Issue by Mqlhaha** [emp-toolkit/emp-ot#53]
When I installed emp-ot with script and try to test it by ```./run ./bin/ot```, segmentation fault happened. 

In https://github.com/emp-toolkit/emp-ot/issues/51#issue-820853085 wangxiao mentioned that the binary is updated and the number of OT to run needs to be specified. So I solved the problem by modifying 
```
(sleep 0.05; $1 1 12345) &  $1 2 12345
```
to 
```
(sleep 0.05; $1 1 12345 $2) &  $1 2 12345 $2
```
and run ```./run ./bin/ot 20 ```

I think the script should be updated or a number of OT should be specified as default in binary to avoid Segmentation fault.

**Comment by wangxiao1254** [comment]
fixed!
