### ISSUE TITLE
In the branch v0.1, why discard iterated.h?

### ISSUE THREAD

**Issue by ArlenaXiong** [emp-toolkit/emp-ot#54]

**Comment by ArlenaXiong** [comment]
the data structure seems changed a lot :(, since my  code needs use SHIterated.

**Comment by wangxiao1254** [comment]
iterated.h was the implementation of an idea in CCS:ALSZ13, however, it is actually not needed in IKNP OTs. Therefore it is deleted. Note that branch v0.1 is not supported anymore. You are encouraged to update your code to use the latest main branch of the code.
