### ISSUE TITLE
emp-ot no longer compiles: Hn used with 5 arguments, but it now only accepts 4

### ISSUE THREAD

**Issue by isheff** [emp-toolkit/emp-ot#56]
This line no longer compiles:
https://github.com/emp-toolkit/emp-ot/blob/2e19a10f317b5e1b9c293b50a3890e87e7c7b9f3/emp-ot/ferret/preot.h#L40

because it uses the `Hn` function with 5 arguments, but it now only has 4 arguments:
https://github.com/emp-toolkit/emp-tool/blob/25f91d1a2aaaa4a1466aba1c51adc850a7812f22/emp-tool/utils/ccrh.h#L43

This was changed in a recent emp-tool commit:
https://github.com/emp-toolkit/emp-tool/pull/124/commits/e9ada69e547b51842c1bd1f9383734e53fad0031

**Comment by wangxiao1254** [comment]
This should be fixed by now
