### ISSUE TITLE
A potential bug which could cause overflow

### ISSUE THREAD

**Issue by gconeice** [emp-toolkit/emp-ot#57]
Hi! We found a bug which could cause overflow in [this file](https://github.com/emp-toolkit/emp-ot/blob/master/emp-ot/ferret/ferret_cot.hpp) at line 231. The round should be uint64_t type rather than int.

Basically, when we was trying to set up a large amount of OTs (about 3 billion), the bound will overflow the int.

**Comment by wangxiao1254** [comment]
This would need some changes across the repo because many interfaces in OT take int as input. We will fix all to uint64_t.

**Comment by gconeice** [comment]
Got it. Thanks!

**Comment by wangxiao1254** [comment]
Let's close it after I fix it :)

**Comment by wangxiao1254** [comment]
please check if it works now. There is some arithmetic on the length so I used int64_t in the end (but I'm sure you don't need 2^63 OTs, so it should be fine)

**Comment by gconeice** [comment]
It works! Thank you very much! Obiviously, no one in the world should currently need 2^63 OTs LMAO.
