### ISSUE TITLE
Correlated send_cot API confusion

### ISSUE THREAD

**Issue by KuraTheDog** [emp-toolkit/emp-ot#60]
The README has the APi for `send_cot` as `ote.send_cot(b0, delta, length);`, which makes sense to me.
Namely, input delta, randomize and set b0, and receiver with choice c gets b0 + c * delta. This is how I understand correlated OT to work.

However, every other instance of `send_cot` in the codebase defines it as `void send_cot(block* data0, int64_t length)`. 
I am unsure of how to use this as a correlated OT, as there is no input delta provided.
From my testing, it randomizes and sets b0, then the receiver gets b0 on choice 0, and some new random b1 on choice 1. It seems like b1 is not correlated at all with b0.
Essentially, this just looks like "send_rot", except the sender doesn't know what the random other b1 is and only learns random b0.

Am I understanding this right? Is the API wrong, or is the readme wrong, or something else?
Any clarification would be appreciated.

**Comment by wangxiao1254** [comment]
The delta is not specified in function but in the class. This is more closely resembles how IKNP/silent OT works.
See https://github.com/emp-toolkit/emp-ot/blob/master/emp-ot/cot.h#L12
For each COT protocol, they provide different ways to specify the Delta and all calls to send_cot will use the same Delta as correlation.

**Comment by KuraTheDog** [comment]
I see. Extracting out the delta, the math makes sense now.

Is there a way to do it with the functionality described in the readme? Namely, provide my own delta that's distinct for every call?

Looking at the API there's setup_send to set s, to set delta, but that's a one time setup and I don't know if it's safe to call it multiple times for each new delta. (Since I think I'll need to call setup_recv every new time too)
Alternately, there is possibly just editing the attribute between calls. This won't work on the first call though since it'll call setup send and override it since it doesn't think it's setup yet.

I'm currently considering doing the first call with setup_send and custom s, then overriding delta for all future calls. Does this work? Is there a better way?

**Comment by wangxiao1254** [comment]
You can always create a new COT object that uses a new Delta. Note that this is what was done in the old API so no efficiency loss.

**Comment by wangxiao1254** [comment]
@wangxiao1254 Fix the readme examples

**Comment by KuraTheDog** [comment]
To clarify, the best way is to make a fresh object each time, calling setup_send (and setup_recv) manually to pass in a fresh custom delta each time? 
Am I able to reuse the same "in_k0" in some way? It doesn't seem like it, as s is used as selector for k0, but I might be wrong. If not, each new instance will need to have setup do a send/recv. Is this step necessary? 
From what I understand of COT, it should be less total communication compared to just implementing it via standard OT. Is it that the "send_cot" itself is nearly free, and [send_cot + setup_send] for each new COT is still cheaper than calling normal send (and not needing new setups)?

**Comment by wangxiao1254** [comment]
> To clarify, the best way is to make a fresh object each time, calling setup_send (and setup_recv) manually to pass in a fresh custom delta each time?
Yes. Note that to avoid redoing the setup it, you will need to send linear communication. This interface allows sublinear communcation for COT

> Am I able to reuse the same "in_k0" in some way? It doesn't seem like it, as s is used as selector for k0, but I might be wrong. If not, each new instance will need to have setup do a send/recv. Is this step necessary?
I think so, unless your application use COT in a specific way
> From what I understand of COT, it should be less total communication compared to just implementing it via standard OT. Is it that the "send_cot" itself is nearly free, and [send_cot + setup_send] for each new COT is still cheaper than calling normal send (and not needing new setups)?
I think you are thinking about a different COT. Here it refers to correlated OT with error plus KOS check. (so not a standard OT)

**Comment by KuraTheDog** [comment]
Thank you, I think this makes sense.

**Comment by wangxiao1254** [comment]
updated in the latest commit.
