### ISSUE TITLE
Questions about replacing some obsolete OT functions

### ISSUE THREAD

**Issue by YFMao15** [emp-toolkit/emp-ot#62]
I am improving some code written in previous version of emp, where it includes several OT classes that cannot be found in today's version. They include:

OTIterated, SHOTIterated, Batcher

I would like to change it to the corresponding function under current version, but I didn't find any proper replacement.

**Comment by wangxiao1254** [comment]
All OT protocols support iteration so we don't put extra interface on that. Batcher is not need as you can now just allocate variables line by line.

**Comment by YFMao15** [comment]
Thanks for your reply. I am wondering about how to replace Batcher object in the following code

        Batcher batcher1, batcher2;
	if(party==ALICE){
		for(int i = 0; i < inner.rows(); ++i) {
			batcher1.add<Integer>(P, inner(i));
			batcher2.add<Integer>(P, (unsigned long)0);
		}
	}
	else{
		for(int i = 0; i < inner.rows(); ++i) {
			batcher1.add<Integer>(P, (unsigned long)0);
			batcher2.add<Integer>(P, inner(i));
		}
	}
	batcher1.make_semi_honest(ALICE);
	batcher2.make_semi_honest(BOB);

**Comment by wangxiao1254** [comment]
xx = Integer(P, inner(i), ALICE);
yy = Integer(P, inner(i), BOB);
