### ISSUE TITLE
random_bool instead of random_block

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ot#65]
Here, the goal is to get 256 random bits:
https://github.com/emp-toolkit/emp-ot/blob/84d98b281318d1af82b3c66a04ce79cf2ccca6f3/emp-ot/iknp.h#L128-L132

Is there a reason why not straight away use  `prg.random_block(&local_r_block, 2);  `?
What is the purpose of the longer route of bool->block ? I just want to make sure I understand the code and am not missing something crucial.

**Comment by wangxiao1254** [comment]
You need both bool and block so I would not say this is a longer route :)
