### ISSUE TITLE
same random value used 3 times

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ot#67]
Hi, here the random is expanded from seed
https://github.com/emp-toolkit/emp-ot/blob/253ff00fe42dd6386f31662eadc2462d164aef3b/emp-ot/iknp.h#L214
then from the same seed 
https://github.com/emp-toolkit/emp-ot/blob/253ff00fe42dd6386f31662eadc2462d164aef3b/emp-ot/iknp.h#L223
and again from the same seed
https://github.com/emp-toolkit/emp-ot/blob/253ff00fe42dd6386f31662eadc2462d164aef3b/emp-ot/iknp.h#L232

The same random values may end up being used in 3 places. Isn't this out of harmony with what the KOS15 paper says that all the values must be random?

**Comment by wangxiao1254** [comment]
good point the second call should use chi[-1]*seed2 as the seed2. I will work on and push a fix now!

**Comment by wangxiao1254** [comment]
Turns out that simply using `chi[-1]*seed2` is not the best solution because `uni_hash_coeff_gen` computes `seed^i`, which becomes `(chi[-1]*seed2)^i`, but we want `chi[-1]*(seed2)^i`.
