### ISSUE TITLE
How to make IKNP OT between 2 precess in local

### ISSUE THREAD

**Issue by boulevard-h** [emp-toolkit/emp-ot#70]

**Comment by boulevard-h** [comment]
I just wanna try use this API to make IKNP OT on my Ubuntu locally. I write a progaram for alice like this:
`#include<stdio.h>
#include<emp-tool/emp-tool.h>
#include<emp-ot/emp-ot.h>

#define length 2
// #define party 'alice'

int main(){
    block b0[length], b1[length];
    bool c[length];
    NetIO io(1==1 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1
    OTNP<NetIO> np(&io); // create a Naor Pinkas OT using the network above
    // if (party == 'alice')
    // ALICE is sender, with b0[i] and b1[i] as messages to send
        np.send(b0, b1, length); 
    // else
    // Bob is receiver, with c[i] as the choice bit 
    // and obtains b0[i] if c[i]==0 and b1[i] if c[i]==1
        // np.recv(b0, c, length);  
}`
but I have some error:
`#include<stdio.h>
#include<emp-tool/emp-tool.h>
#include<emp-ot/emp-ot.h>

#define length 2
// #define party 'alice'

int main(){
    block b0[length], b1[length];
    bool c[length];
    NetIO io(1==1 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1
    OTNP<NetIO> np(&io); // create a Naor Pinkas OT using the network above
    // if (party == 'alice')
    // ALICE is sender, with b0[i] and b1[i] as messages to send
        np.send(b0, b1, length); 
    // else
    // Bob is receiver, with c[i] as the choice bit 
    // and obtains b0[i] if c[i]==0 and b1[i] if c[i]==1
        // np.recv(b0, c, length);  
}`
I'm not familiar with NetIO and block type used in your demo, how can I make it?
BTW, I have tried test bin file, it passed.

**Comment by wangxiao1254** [comment]
If you are using cmake, make sure to link `EMP-OT_LIBRARIES`; if you are using g++ to compile directly, make sure to link openssl and emp-tool mannualy! The error shows up because you did not include the libraries and probably also did not include the headers when call g++.

**Comment by boulevard-h** [comment]
> cause you did not include the libraries and probably also did not include the headers when ca

Thanks for ur answer. I add emp-tool in include and use g++ to link it by -L emp-tool/emp-tool.h.
But I dont now which specific .h file I need to include and link in OpenSSL. Can you help me?

**Comment by wangxiao1254** [comment]
I recommend you work in the following steps:
1. use CMake so that you know your program works fine.
2. add `-I` to include headers and `-L` to include libraries. If you emp and openssl are all installed at default location, something like the following should work
`g++ test.cpp -lemp-tool -std=c++11 -march=native -pthread -Wall -funroll-loops -lcrypto` You may need to add `-I[openssl_header_location] -L[openssl_library_location]` if your openssl is not at the default location

**Comment by boulevard-h** [comment]
Thanks a lot, now I compiled 2 files successfully for Alice and Bob, and I run these 2 .out files. It shows 'connected'  in both Bob and Alice's programs. I think it works!
But the 2 programs shut down after print this message, how can I use this to send & receive some bit stream or message?
My test code for Alice
`
#include<stdio.h>
#include<emp-tool/emp-tool.h>
#include<emp-ot/emp-ot.h>
#include<openssl/crypto.h>

#define length 2


int main(){
    block b0[length], b1[length];
    bool c[length];
    NetIO io(1==1 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1
    OTNP<NetIO> np(&io); // create a Naor Pinkas OT using the network above
    np.send(b0, b1, length); 

}
`

Bob's:
`
#include<stdio.h>
#include<emp-tool/emp-tool.h>
#include<emp-ot/emp-ot.h>
#include<openssl/crypto.h>

#define length 2

int main(){
    block b0[length], b1[length];
    bool c[length];
    NetIO io(1==0 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1
    OTNP<NetIO> np(&io); // create a Naor Pinkas OT using the network above
    np.recv(b0, c, length); 

}
`

**Comment by boulevard-h** [comment]
> Thanks a lot, now I compiled 2 files successfully for Alice and Bob, and I run these 2 .out files. It shows 'connected' in both Bob and Alice's programs. I think it works! But the 2 programs shut down after print this message, how can I use this to send & receive some bit stream or message? My test code for Alice ` #include<stdio.h> #include<emp-tool/emp-tool.h> #include<emp-ot/emp-ot.h> #include<openssl/crypto.h>
> 
> #define length 2
> 
> int main(){ block b0[length], b1[length]; bool c[length]; NetIO io(1==1 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1 OTNP np(&io); // create a Naor Pinkas OT using the network above np.send(b0, b1, length);
> 
> } `
> 
> Bob's: ` #include<stdio.h> #include<emp-tool/emp-tool.h> #include<emp-ot/emp-ot.h> #include<openssl/crypto.h>
> 
> #define length 2
> 
> int main(){ block b0[length], b1[length]; bool c[length]; NetIO io(1==0 ? nullptr:"127.0.0.1", 8080); // Create a network with Bob connecting to 127.0.0.1 OTNP np(&io); // create a Naor Pinkas OT using the network above np.recv(b0, c, length);
> 
> } `

This question has solved now.
