### ISSUE TITLE
KOS15 mult without reduction

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ot#71]
Hi, I noticed that the code does not follow exactly what the KOS15 paper says on page 8
"where the vectors t_j , q_j , χ_j are viewed as elements of F_2^κ and multiplications
are performed in *this* finite field"
So, multiplications must be done in the field 2^128. So when multiplying 2 128-bit elements, there must be reduction of the product.
But in the code it uses multiplication without reduction.
https://github.com/emp-toolkit/emp-ot/blob/5ef31873932096e672039bf41bc5ce5ac60f0bae/emp-ot/iknp.h#L235

I understand that the reason to not reduce is performance. I just wanted to double-check with you if doing so (i.e. not reducing) does not pose a security risk?

**Comment by wangxiao1254** [comment]
See https://eprint.iacr.org/2015/546.pdf page 14 Implementation Optimizations
