### ISSUE TITLE
How to change the parameter k of iknp?

### ISSUE THREAD

**Issue by boulevard-h** [emp-toolkit/emp-ot#72]
According to iknp03, it uses k-times 1-out-2 OTs to make n-times 1-out-2 OT. In your API, there are parameters b1, b2 and length. b1, b2 is the data, and length is the n. But how can I change the k ? Or what's the default k=f(n) in your iknp OT?

**Comment by wangxiao1254** [comment]
See function at https://github.com/emp-toolkit/emp-ot/blob/master/emp-ot/iknp.h#L39
