### ISSUE TITLE
Is it possible to test and measure cost of communication?

### ISSUE THREAD

**Issue by ppppbamzy** [emp-toolkit/emp-ot#80]
I am reading the ferret paper, and wonder:  by bootstrapped iterations do the amount of COTs produced (and hence the cost of communication) increase in a stepwise way? I.e. is it true that producing M+1 COTs and M+n COTs cost the same, while M+n+1 COTs (or M+2n) costs more?
Is there a functionality for measuring the cost of communication so as to check this thing?

**Comment by wangxiao1254** [comment]
Essentially, using default parameters, you can only generate M+cn OTs for some integer c, if you want something in the middle, you would waste some OT. You could get precisely the number of OT you need but then you need to tweak the LPN parameters.

You can get the communication by accumulating `io[i]->counter`, which will tell you the amount of data in bytes that has been sent up to that point from a party (the data received should be the data sent of the other party).

**Comment by ppppbamzy** [comment]
Thanks a lot.
