### ISSUE TITLE
An abnormal speed result

### ISSUE THREAD

**Issue by Xenooooooooo** [emp-toolkit/emp-ot#83]
Hello, professor. I was using emp-ot for some speeding test. After the installation, I was using `./run ./bin/test_ot 24` to test generating $2^{24}$ OTs, but the result was quite frustrating. The screenshot is as below.

![image](https://user-images.githubusercontent.com/90409731/223613813-71e1f634-7648-403e-bc8c-74d80441883f.png)

I've tried generating $2^{24}$ and $2^{25}$ OTs, and Ferret is evidently **slower** than the primitive IKNP protocol. I just can't figure it out. 

By the way, the enviroment for the test is Ubuntu 22.04.2 LTS (jammy), 4 GB RAM, 60 GB ROM, Intel® Core™ i7-8550U CPU @ 1.80GHz with 4 Cores, VMWare.

**Comment by wangxiao1254** [comment]
Ferret is slower than IKNP under 1 thread.

**Comment by Xenooooooooo** [comment]
Right, I got that.
Thanks for your help and quick response, professor.
