### ISSUE TITLE
Problems of threading when conducting test_ot

### ISSUE THREAD

**Issue by Xenooooooooo** [emp-toolkit/emp-ot#84]
Hello, professor. Please pardon me for disturbing you again.
In the file ./test/ot.cpp, line 4, there is a global variant for setting the thread. Defaultly, it is 1.

When I set it to 2, recompile the whole project and re-run the test_ot under 2^24, the ferret test is SEG.
 
![image](https://user-images.githubusercontent.com/90409731/224477246-76875552-d202-44c1-a314-f91a2b2c323a.png)

Do you have any idea what's going on in this problem?

**Comment by Xenooooooooo** [comment]
It's the same situation when the thread is setted to 3, 4 or 5.

**Comment by Xenooooooooo** [comment]
And an another question, in ./test/ferret.cpp, there are two tests, Ferret RCOT and Ferret RCOT inplace. 

What's the difference between these two tests? Are they just different with the places that generate RCOTs?

**Comment by wangxiao1254** [comment]
test/ot.cpp does not support setting thread to any other value.
inplace has a different interface and less memory copy.

**Comment by Xenooooooooo** [comment]
Thanks a lot for your response, professor.

And another question, why there are two tests in ./test/ferret.cpp ? If only the interfaces are different, and the data structure of the generated COTs / OTs is the same, which interface is recommended to use when calling EMP-OT library for building upper layer protocols? And reasons?

**Comment by wangxiao1254** [comment]
inplace is better if you know how many OT you want to use AND you have enough memory. the difference is usually small.
