### ISSUE TITLE
KOS check chi is not sampled using F_rand

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ot#86]
HI. Currently in emp-ot the OT receiver unilaterally samples a chi seed and sends it to the OT sender:

https://github.com/emp-toolkit/emp-ot/blob/eb0daf2a7a88c44b419f6d1276dc19e66f80776f/emp-ot/iknp.h#L173-L176

but the KOS paper says that chi should be sampled by the functionality F_rand  (e.g. a coin-toss protocol)

Is it secure the way it is implemented now?

**Comment by themighty1** [comment]
@wangxiao1254 , could you please have a look at this. This may be a serious vulnerability.

**Comment by wangxiao1254** [comment]
in their latest version, they have updated it to let one party sample the seed.

**Comment by themighty1** [comment]
Thanks for pointing it out @wangxiao1254 but I still see `F_rand` used in the latest paper:

https://eprint.iacr.org/2015/546 (updated on 2022-09-16)

![Screenshot from 2024-02-29 09-04-32](https://github.com/emp-toolkit/emp-ot/assets/555272/bdff37ee-d335-48f5-8d00-c967fe050c4c)

**Comment by wangxiao1254** [comment]
See figure 10
