### ISSUE TITLE
Question about SPCOT in ferret.

### ISSUE THREAD

**Issue by AdijeShen** [emp-toolkit/emp-ot#88]
Hello, professor. In SPCOT, after generating the GGM tree leaves, sender set each leaves' LSB to zero in these lines: 

https://github.com/emp-toolkit/emp-ot/blob/eb0daf2a7a88c44b419f6d1276dc19e66f80776f/emp-ot/ferret/spcot_sender.h#L52-L56

I can't find out the reason for this in ferret's paper.

**Comment by wangxiao1254** [comment]
This is to embed the choice bit at LSB.

**Comment by AdijeShen** [comment]
Dear Professor,

I appreciate your guidance, and I'm glad to report that I have been able to fully comprehend the process of the Ferret COT as well as the concept of embedding receiver's choice bit at the LSB.

There's another aspect I would like to discuss with you. In the MPCOT protocol, as described in the Ferret paper, two approaches are presented:

The first one is a straightforward combination of SPCOT that involves invoking the SPCOT protocol $t$ times, each of length $n$, and aggregating the results to produce an MPCOT of $(n,t)$.
The second method suggests the use of cuckoo hashing to reduce the length of each SPCOT, as depicted in Figure 7.
However, upon reviewing the implementation in EMP-OT, it appears that the strategy has been adjusted to call the SPCOT protocol $t$ times, each of length $\lfloor n/t \rceil$, and then concatenate these results to generate an MPCOT of $(n,t)$.

I'm curious to understand whether this adjustment was made as a further enhancement post-publication of the paper or if it was done merely to facilitate implementation. Furthermore, I'd like to know how this alteration impacts the security properties of the Ferret protocol.

Thank you in advance for your insights on this matter.

**Comment by wangxiao1254** [comment]
Do note that there are two types of LPN assumptions depending on the noise distribution. IF we use t times of n-sized noise, that would be ordinary LPN assumption where noise index are uniform. Here we use regular noise distribution, where we assume one uniform noise index in each n/t segment. See "Compressed VOLE" from CCS for more details.
